//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B_Gimnasio.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calendario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Calendario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        private int dniProfesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private B_Gimnasio.ServiceReference1.Clases[] clasesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int dniProfesor {
            get {
                return this.dniProfesorField;
            }
            set {
                if ((this.dniProfesorField.Equals(value) != true)) {
                    this.dniProfesorField = value;
                    this.RaisePropertyChanged("dniProfesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloField, value) != true)) {
                    this.tituloField = value;
                    this.RaisePropertyChanged("titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public B_Gimnasio.ServiceReference1.Clases[] clases {
            get {
                return this.clasesField;
            }
            set {
                if ((object.ReferenceEquals(this.clasesField, value) != true)) {
                    this.clasesField = value;
                    this.RaisePropertyChanged("clases");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clases", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Clases : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string temaField;
        
        private int cantAlumnosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaInicioField;
        
        private int idProfesorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tema {
            get {
                return this.temaField;
            }
            set {
                if ((object.ReferenceEquals(this.temaField, value) != true)) {
                    this.temaField = value;
                    this.RaisePropertyChanged("tema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int cantAlumnos {
            get {
                return this.cantAlumnosField;
            }
            set {
                if ((this.cantAlumnosField.Equals(value) != true)) {
                    this.cantAlumnosField = value;
                    this.RaisePropertyChanged("cantAlumnos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaInicioField, value) != true)) {
                    this.fechaInicioField = value;
                    this.RaisePropertyChanged("fechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int idProfesor {
            get {
                return this.idProfesorField;
            }
            set {
                if ((this.idProfesorField.Equals(value) != true)) {
                    this.idProfesorField = value;
                    this.RaisePropertyChanged("idProfesor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento profe del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostProfesor", ReplyAction="*")]
        B_Gimnasio.ServiceReference1.PostProfesorResponse PostProfesor(B_Gimnasio.ServiceReference1.PostProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostProfesor", ReplyAction="*")]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.PostProfesorResponse> PostProfesorAsync(B_Gimnasio.ServiceReference1.PostProfesorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetProfesoresResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProfesores", ReplyAction="*")]
        B_Gimnasio.ServiceReference1.GetProfesoresResponse GetProfesores(B_Gimnasio.ServiceReference1.GetProfesoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProfesores", ReplyAction="*")]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.GetProfesoresResponse> GetProfesoresAsync(B_Gimnasio.ServiceReference1.GetProfesoresRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetProfesorResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProfesor", ReplyAction="*")]
        B_Gimnasio.ServiceReference1.GetProfesorResponse GetProfesor(B_Gimnasio.ServiceReference1.GetProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProfesor", ReplyAction="*")]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.GetProfesorResponse> GetProfesorAsync(B_Gimnasio.ServiceReference1.GetProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProfesor", ReplyAction="*")]
        void DeleteProfesor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProfesor", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteProfesorAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nuevoProfe del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutProfesor", ReplyAction="*")]
        B_Gimnasio.ServiceReference1.PutProfesorResponse PutProfesor(B_Gimnasio.ServiceReference1.PutProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutProfesor", ReplyAction="*")]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.PutProfesorResponse> PutProfesorAsync(B_Gimnasio.ServiceReference1.PutProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularSueldoProfe", ReplyAction="*")]
        int CalcularSueldoProfe(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularSueldoProfe", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CalcularSueldoProfeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClasesSinAlumnos", ReplyAction="*")]
        bool ClasesSinAlumnos(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClasesSinAlumnos", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ClasesSinAlumnosAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetClasesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClases", ReplyAction="*")]
        B_Gimnasio.ServiceReference1.GetClasesResponse GetClases(B_Gimnasio.ServiceReference1.GetClasesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClases", ReplyAction="*")]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.GetClasesResponse> GetClasesAsync(B_Gimnasio.ServiceReference1.GetClasesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetClaseResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClase", ReplyAction="*")]
        B_Gimnasio.ServiceReference1.GetClaseResponse GetClase(B_Gimnasio.ServiceReference1.GetClaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClase", ReplyAction="*")]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.GetClaseResponse> GetClaseAsync(B_Gimnasio.ServiceReference1.GetClaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteClase", ReplyAction="*")]
        void DeleteClase(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteClase", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteClaseAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nuevaClase del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutClases", ReplyAction="*")]
        B_Gimnasio.ServiceReference1.PutClasesResponse PutClases(B_Gimnasio.ServiceReference1.PutClasesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutClases", ReplyAction="*")]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.PutClasesResponse> PutClasesAsync(B_Gimnasio.ServiceReference1.PutClasesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento clase del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostClase", ReplyAction="*")]
        B_Gimnasio.ServiceReference1.PostClaseResponse PostClase(B_Gimnasio.ServiceReference1.PostClaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostClase", ReplyAction="*")]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.PostClaseResponse> PostClaseAsync(B_Gimnasio.ServiceReference1.PostClaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostProfesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostProfesor", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.PostProfesorRequestBody Body;
        
        public PostProfesorRequest() {
        }
        
        public PostProfesorRequest(B_Gimnasio.ServiceReference1.PostProfesorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostProfesorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B_Gimnasio.ServiceReference1.Calendario profe;
        
        public PostProfesorRequestBody() {
        }
        
        public PostProfesorRequestBody(B_Gimnasio.ServiceReference1.Calendario profe) {
            this.profe = profe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostProfesorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostProfesorResponse", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.PostProfesorResponseBody Body;
        
        public PostProfesorResponse() {
        }
        
        public PostProfesorResponse(B_Gimnasio.ServiceReference1.PostProfesorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostProfesorResponseBody {
        
        public PostProfesorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfesoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfesores", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.GetProfesoresRequestBody Body;
        
        public GetProfesoresRequest() {
        }
        
        public GetProfesoresRequest(B_Gimnasio.ServiceReference1.GetProfesoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProfesoresRequestBody {
        
        public GetProfesoresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfesoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfesoresResponse", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.GetProfesoresResponseBody Body;
        
        public GetProfesoresResponse() {
        }
        
        public GetProfesoresResponse(B_Gimnasio.ServiceReference1.GetProfesoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProfesoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B_Gimnasio.ServiceReference1.Calendario[] GetProfesoresResult;
        
        public GetProfesoresResponseBody() {
        }
        
        public GetProfesoresResponseBody(B_Gimnasio.ServiceReference1.Calendario[] GetProfesoresResult) {
            this.GetProfesoresResult = GetProfesoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfesor", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.GetProfesorRequestBody Body;
        
        public GetProfesorRequest() {
        }
        
        public GetProfesorRequest(B_Gimnasio.ServiceReference1.GetProfesorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProfesorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetProfesorRequestBody() {
        }
        
        public GetProfesorRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfesorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfesorResponse", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.GetProfesorResponseBody Body;
        
        public GetProfesorResponse() {
        }
        
        public GetProfesorResponse(B_Gimnasio.ServiceReference1.GetProfesorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProfesorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B_Gimnasio.ServiceReference1.Calendario GetProfesorResult;
        
        public GetProfesorResponseBody() {
        }
        
        public GetProfesorResponseBody(B_Gimnasio.ServiceReference1.Calendario GetProfesorResult) {
            this.GetProfesorResult = GetProfesorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutProfesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutProfesor", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.PutProfesorRequestBody Body;
        
        public PutProfesorRequest() {
        }
        
        public PutProfesorRequest(B_Gimnasio.ServiceReference1.PutProfesorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutProfesorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B_Gimnasio.ServiceReference1.Calendario nuevoProfe;
        
        public PutProfesorRequestBody() {
        }
        
        public PutProfesorRequestBody(B_Gimnasio.ServiceReference1.Calendario nuevoProfe) {
            this.nuevoProfe = nuevoProfe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutProfesorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutProfesorResponse", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.PutProfesorResponseBody Body;
        
        public PutProfesorResponse() {
        }
        
        public PutProfesorResponse(B_Gimnasio.ServiceReference1.PutProfesorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PutProfesorResponseBody {
        
        public PutProfesorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClasesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClases", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.GetClasesRequestBody Body;
        
        public GetClasesRequest() {
        }
        
        public GetClasesRequest(B_Gimnasio.ServiceReference1.GetClasesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetClasesRequestBody {
        
        public GetClasesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClasesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClasesResponse", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.GetClasesResponseBody Body;
        
        public GetClasesResponse() {
        }
        
        public GetClasesResponse(B_Gimnasio.ServiceReference1.GetClasesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClasesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B_Gimnasio.ServiceReference1.Clases[] GetClasesResult;
        
        public GetClasesResponseBody() {
        }
        
        public GetClasesResponseBody(B_Gimnasio.ServiceReference1.Clases[] GetClasesResult) {
            this.GetClasesResult = GetClasesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClase", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.GetClaseRequestBody Body;
        
        public GetClaseRequest() {
        }
        
        public GetClaseRequest(B_Gimnasio.ServiceReference1.GetClaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetClaseRequestBody() {
        }
        
        public GetClaseRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.GetClaseResponseBody Body;
        
        public GetClaseResponse() {
        }
        
        public GetClaseResponse(B_Gimnasio.ServiceReference1.GetClaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B_Gimnasio.ServiceReference1.Clases GetClaseResult;
        
        public GetClaseResponseBody() {
        }
        
        public GetClaseResponseBody(B_Gimnasio.ServiceReference1.Clases GetClaseResult) {
            this.GetClaseResult = GetClaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutClasesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutClases", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.PutClasesRequestBody Body;
        
        public PutClasesRequest() {
        }
        
        public PutClasesRequest(B_Gimnasio.ServiceReference1.PutClasesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutClasesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B_Gimnasio.ServiceReference1.Clases nuevaClase;
        
        public PutClasesRequestBody() {
        }
        
        public PutClasesRequestBody(B_Gimnasio.ServiceReference1.Clases nuevaClase) {
            this.nuevaClase = nuevaClase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutClasesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutClasesResponse", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.PutClasesResponseBody Body;
        
        public PutClasesResponse() {
        }
        
        public PutClasesResponse(B_Gimnasio.ServiceReference1.PutClasesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PutClasesResponseBody {
        
        public PutClasesResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostClaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostClase", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.PostClaseRequestBody Body;
        
        public PostClaseRequest() {
        }
        
        public PostClaseRequest(B_Gimnasio.ServiceReference1.PostClaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostClaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B_Gimnasio.ServiceReference1.Clases clase;
        
        public PostClaseRequestBody() {
        }
        
        public PostClaseRequestBody(B_Gimnasio.ServiceReference1.Clases clase) {
            this.clase = clase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostClaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostClaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public B_Gimnasio.ServiceReference1.PostClaseResponseBody Body;
        
        public PostClaseResponse() {
        }
        
        public PostClaseResponse(B_Gimnasio.ServiceReference1.PostClaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostClaseResponseBody {
        
        public PostClaseResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : B_Gimnasio.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<B_Gimnasio.ServiceReference1.WebService1Soap>, B_Gimnasio.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B_Gimnasio.ServiceReference1.PostProfesorResponse B_Gimnasio.ServiceReference1.WebService1Soap.PostProfesor(B_Gimnasio.ServiceReference1.PostProfesorRequest request) {
            return base.Channel.PostProfesor(request);
        }
        
        public void PostProfesor(B_Gimnasio.ServiceReference1.Calendario profe) {
            B_Gimnasio.ServiceReference1.PostProfesorRequest inValue = new B_Gimnasio.ServiceReference1.PostProfesorRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.PostProfesorRequestBody();
            inValue.Body.profe = profe;
            B_Gimnasio.ServiceReference1.PostProfesorResponse retVal = ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).PostProfesor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.PostProfesorResponse> B_Gimnasio.ServiceReference1.WebService1Soap.PostProfesorAsync(B_Gimnasio.ServiceReference1.PostProfesorRequest request) {
            return base.Channel.PostProfesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.PostProfesorResponse> PostProfesorAsync(B_Gimnasio.ServiceReference1.Calendario profe) {
            B_Gimnasio.ServiceReference1.PostProfesorRequest inValue = new B_Gimnasio.ServiceReference1.PostProfesorRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.PostProfesorRequestBody();
            inValue.Body.profe = profe;
            return ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).PostProfesorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B_Gimnasio.ServiceReference1.GetProfesoresResponse B_Gimnasio.ServiceReference1.WebService1Soap.GetProfesores(B_Gimnasio.ServiceReference1.GetProfesoresRequest request) {
            return base.Channel.GetProfesores(request);
        }
        
        public B_Gimnasio.ServiceReference1.Calendario[] GetProfesores() {
            B_Gimnasio.ServiceReference1.GetProfesoresRequest inValue = new B_Gimnasio.ServiceReference1.GetProfesoresRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.GetProfesoresRequestBody();
            B_Gimnasio.ServiceReference1.GetProfesoresResponse retVal = ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).GetProfesores(inValue);
            return retVal.Body.GetProfesoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.GetProfesoresResponse> B_Gimnasio.ServiceReference1.WebService1Soap.GetProfesoresAsync(B_Gimnasio.ServiceReference1.GetProfesoresRequest request) {
            return base.Channel.GetProfesoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.GetProfesoresResponse> GetProfesoresAsync() {
            B_Gimnasio.ServiceReference1.GetProfesoresRequest inValue = new B_Gimnasio.ServiceReference1.GetProfesoresRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.GetProfesoresRequestBody();
            return ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).GetProfesoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B_Gimnasio.ServiceReference1.GetProfesorResponse B_Gimnasio.ServiceReference1.WebService1Soap.GetProfesor(B_Gimnasio.ServiceReference1.GetProfesorRequest request) {
            return base.Channel.GetProfesor(request);
        }
        
        public B_Gimnasio.ServiceReference1.Calendario GetProfesor(int id) {
            B_Gimnasio.ServiceReference1.GetProfesorRequest inValue = new B_Gimnasio.ServiceReference1.GetProfesorRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.GetProfesorRequestBody();
            inValue.Body.id = id;
            B_Gimnasio.ServiceReference1.GetProfesorResponse retVal = ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).GetProfesor(inValue);
            return retVal.Body.GetProfesorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.GetProfesorResponse> B_Gimnasio.ServiceReference1.WebService1Soap.GetProfesorAsync(B_Gimnasio.ServiceReference1.GetProfesorRequest request) {
            return base.Channel.GetProfesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.GetProfesorResponse> GetProfesorAsync(int id) {
            B_Gimnasio.ServiceReference1.GetProfesorRequest inValue = new B_Gimnasio.ServiceReference1.GetProfesorRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.GetProfesorRequestBody();
            inValue.Body.id = id;
            return ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).GetProfesorAsync(inValue);
        }
        
        public void DeleteProfesor(int id) {
            base.Channel.DeleteProfesor(id);
        }
        
        public System.Threading.Tasks.Task DeleteProfesorAsync(int id) {
            return base.Channel.DeleteProfesorAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B_Gimnasio.ServiceReference1.PutProfesorResponse B_Gimnasio.ServiceReference1.WebService1Soap.PutProfesor(B_Gimnasio.ServiceReference1.PutProfesorRequest request) {
            return base.Channel.PutProfesor(request);
        }
        
        public void PutProfesor(B_Gimnasio.ServiceReference1.Calendario nuevoProfe) {
            B_Gimnasio.ServiceReference1.PutProfesorRequest inValue = new B_Gimnasio.ServiceReference1.PutProfesorRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.PutProfesorRequestBody();
            inValue.Body.nuevoProfe = nuevoProfe;
            B_Gimnasio.ServiceReference1.PutProfesorResponse retVal = ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).PutProfesor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.PutProfesorResponse> B_Gimnasio.ServiceReference1.WebService1Soap.PutProfesorAsync(B_Gimnasio.ServiceReference1.PutProfesorRequest request) {
            return base.Channel.PutProfesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.PutProfesorResponse> PutProfesorAsync(B_Gimnasio.ServiceReference1.Calendario nuevoProfe) {
            B_Gimnasio.ServiceReference1.PutProfesorRequest inValue = new B_Gimnasio.ServiceReference1.PutProfesorRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.PutProfesorRequestBody();
            inValue.Body.nuevoProfe = nuevoProfe;
            return ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).PutProfesorAsync(inValue);
        }
        
        public int CalcularSueldoProfe(int id) {
            return base.Channel.CalcularSueldoProfe(id);
        }
        
        public System.Threading.Tasks.Task<int> CalcularSueldoProfeAsync(int id) {
            return base.Channel.CalcularSueldoProfeAsync(id);
        }
        
        public bool ClasesSinAlumnos(int id) {
            return base.Channel.ClasesSinAlumnos(id);
        }
        
        public System.Threading.Tasks.Task<bool> ClasesSinAlumnosAsync(int id) {
            return base.Channel.ClasesSinAlumnosAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B_Gimnasio.ServiceReference1.GetClasesResponse B_Gimnasio.ServiceReference1.WebService1Soap.GetClases(B_Gimnasio.ServiceReference1.GetClasesRequest request) {
            return base.Channel.GetClases(request);
        }
        
        public B_Gimnasio.ServiceReference1.Clases[] GetClases() {
            B_Gimnasio.ServiceReference1.GetClasesRequest inValue = new B_Gimnasio.ServiceReference1.GetClasesRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.GetClasesRequestBody();
            B_Gimnasio.ServiceReference1.GetClasesResponse retVal = ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).GetClases(inValue);
            return retVal.Body.GetClasesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.GetClasesResponse> B_Gimnasio.ServiceReference1.WebService1Soap.GetClasesAsync(B_Gimnasio.ServiceReference1.GetClasesRequest request) {
            return base.Channel.GetClasesAsync(request);
        }
        
        public System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.GetClasesResponse> GetClasesAsync() {
            B_Gimnasio.ServiceReference1.GetClasesRequest inValue = new B_Gimnasio.ServiceReference1.GetClasesRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.GetClasesRequestBody();
            return ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).GetClasesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B_Gimnasio.ServiceReference1.GetClaseResponse B_Gimnasio.ServiceReference1.WebService1Soap.GetClase(B_Gimnasio.ServiceReference1.GetClaseRequest request) {
            return base.Channel.GetClase(request);
        }
        
        public B_Gimnasio.ServiceReference1.Clases GetClase(int id) {
            B_Gimnasio.ServiceReference1.GetClaseRequest inValue = new B_Gimnasio.ServiceReference1.GetClaseRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.GetClaseRequestBody();
            inValue.Body.id = id;
            B_Gimnasio.ServiceReference1.GetClaseResponse retVal = ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).GetClase(inValue);
            return retVal.Body.GetClaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.GetClaseResponse> B_Gimnasio.ServiceReference1.WebService1Soap.GetClaseAsync(B_Gimnasio.ServiceReference1.GetClaseRequest request) {
            return base.Channel.GetClaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.GetClaseResponse> GetClaseAsync(int id) {
            B_Gimnasio.ServiceReference1.GetClaseRequest inValue = new B_Gimnasio.ServiceReference1.GetClaseRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.GetClaseRequestBody();
            inValue.Body.id = id;
            return ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).GetClaseAsync(inValue);
        }
        
        public void DeleteClase(int id) {
            base.Channel.DeleteClase(id);
        }
        
        public System.Threading.Tasks.Task DeleteClaseAsync(int id) {
            return base.Channel.DeleteClaseAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B_Gimnasio.ServiceReference1.PutClasesResponse B_Gimnasio.ServiceReference1.WebService1Soap.PutClases(B_Gimnasio.ServiceReference1.PutClasesRequest request) {
            return base.Channel.PutClases(request);
        }
        
        public void PutClases(B_Gimnasio.ServiceReference1.Clases nuevaClase) {
            B_Gimnasio.ServiceReference1.PutClasesRequest inValue = new B_Gimnasio.ServiceReference1.PutClasesRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.PutClasesRequestBody();
            inValue.Body.nuevaClase = nuevaClase;
            B_Gimnasio.ServiceReference1.PutClasesResponse retVal = ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).PutClases(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.PutClasesResponse> B_Gimnasio.ServiceReference1.WebService1Soap.PutClasesAsync(B_Gimnasio.ServiceReference1.PutClasesRequest request) {
            return base.Channel.PutClasesAsync(request);
        }
        
        public System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.PutClasesResponse> PutClasesAsync(B_Gimnasio.ServiceReference1.Clases nuevaClase) {
            B_Gimnasio.ServiceReference1.PutClasesRequest inValue = new B_Gimnasio.ServiceReference1.PutClasesRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.PutClasesRequestBody();
            inValue.Body.nuevaClase = nuevaClase;
            return ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).PutClasesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B_Gimnasio.ServiceReference1.PostClaseResponse B_Gimnasio.ServiceReference1.WebService1Soap.PostClase(B_Gimnasio.ServiceReference1.PostClaseRequest request) {
            return base.Channel.PostClase(request);
        }
        
        public void PostClase(B_Gimnasio.ServiceReference1.Clases clase) {
            B_Gimnasio.ServiceReference1.PostClaseRequest inValue = new B_Gimnasio.ServiceReference1.PostClaseRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.PostClaseRequestBody();
            inValue.Body.clase = clase;
            B_Gimnasio.ServiceReference1.PostClaseResponse retVal = ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).PostClase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.PostClaseResponse> B_Gimnasio.ServiceReference1.WebService1Soap.PostClaseAsync(B_Gimnasio.ServiceReference1.PostClaseRequest request) {
            return base.Channel.PostClaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<B_Gimnasio.ServiceReference1.PostClaseResponse> PostClaseAsync(B_Gimnasio.ServiceReference1.Clases clase) {
            B_Gimnasio.ServiceReference1.PostClaseRequest inValue = new B_Gimnasio.ServiceReference1.PostClaseRequest();
            inValue.Body = new B_Gimnasio.ServiceReference1.PostClaseRequestBody();
            inValue.Body.clase = clase;
            return ((B_Gimnasio.ServiceReference1.WebService1Soap)(this)).PostClaseAsync(inValue);
        }
    }
}
